In [4]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True) #drop first and last column

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# **Train Test Split**

syntax: df.iloc[rows, columns] , iloc means index-based selection.

**df.iloc[ : , 1 : ] ----->  all rows , columns 1 → end**

**df.iloc[:, 0]** ----> all rows,column 0 , Column 0 is the diagnosis column.

**test_size = 0.2** -----> 20% → test set ,80% → training set

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#**Scaling**

In [9]:
scaler = StandardScaler() #This creates the scaler object.Think of it as a tool that will learn: feature means,feature standard deviations.But nothing happens yet.

X_train = scaler.fit_transform(X_train) #Two things happen here.
#Step 1:— fit() The scaler learns statistics from the training data.For each feature it calculates:mean standard deviation
#Step 2:— transform() Then it scales the training data using:(𝑥−𝑚𝑒𝑎𝑛)/𝑠𝑡𝑑 So fit_transform() means: learn statistics + scale the data

X_test = scaler.transform(X_test)
#We DO NOT use fit_transform here.We only use: transform() Why? Because we must use the same statistics learned from training data.
#If we ran fit on the test data, the model would accidentally peek at the test set, which is cheating.

In [10]:
X_train

array([[-0.48271058,  0.58666852, -0.483422  , ...,  0.10548512,
         0.09459804,  0.50737767],
       [-0.24789267,  0.5890278 , -0.24553944, ...,  0.73239957,
         1.24096723,  0.71267883],
       [ 1.558176  , -0.2673925 ,  1.5166473 , ...,  1.73826976,
         1.0772002 , -0.34028033],
       ...,
       [-0.5870741 ,  2.1036885 , -0.61037705, ..., -0.6639666 ,
        -0.7401368 , -0.10622551],
       [ 0.22754114, -1.08842353,  0.14418304, ..., -0.5331255 ,
        -0.91980354, -1.28627587],
       [-0.72042749, -1.14976493, -0.6997939 , ..., -0.69484447,
        -0.9277534 , -0.14072991]])

In [11]:
y_train #notice it gives strings and nn cant work on that , that is why we will have to transform these into numbers through label encoding

88     B
44     M
282    M
472    B
223    M
      ..
415    B
155    B
452    B
511    B
540    B
Name: diagnosis, Length: 455, dtype: object

#**Label Encoding**

In [12]:
encoder = LabelEncoder() #This creates a label encoder object.It will learn how to map labels: B → 0 , M → 1


y_train = encoder.fit_transform(y_train) #Two things happen:
#Step 1:— fit()  The encoder looks at the training labels and finds unique classes: [B, M] It assigns numbers: B → 0 M → 1
#Step 2:— transform()  It converts the labels. Example:  [M, B, B, M] becomes [1, 0, 0, 1]


y_test = encoder.transform(y_test) #we must use the same mapping learned from the training set.
#If we ran fit on the test set, we might accidentally create a different mapping, which would break the model.

In [13]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

#**Numpy Arrays to PyTorch Tensors**

In [14]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

#**Dataset Class**

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#**Definig The Model**

In [19]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

#Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

In [23]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

#**Training Pipline**

In [24]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.3462645411491394
Epoch: 2, Loss: 0.17589008808135986
Epoch: 3, Loss: 0.10239393264055252
Epoch: 4, Loss: 0.12509632110595703
Epoch: 5, Loss: 0.13503670692443848
Epoch: 6, Loss: 0.1061587855219841
Epoch: 7, Loss: 0.1389441192150116
Epoch: 8, Loss: 0.09276226907968521
Epoch: 9, Loss: 0.03298380225896835
Epoch: 10, Loss: 0.09542333334684372
Epoch: 11, Loss: 0.1760343760251999
Epoch: 12, Loss: 0.1436048448085785
Epoch: 13, Loss: 0.08361896127462387
Epoch: 14, Loss: 0.11127454787492752
Epoch: 15, Loss: 0.03076929785311222
Epoch: 16, Loss: 0.04107517749071121
Epoch: 17, Loss: 0.031884267926216125
Epoch: 18, Loss: 0.059415753930807114
Epoch: 19, Loss: 0.06649076193571091
Epoch: 20, Loss: 0.06891769915819168
Epoch: 21, Loss: 0.08211132138967514
Epoch: 22, Loss: 0.10921497642993927
Epoch: 23, Loss: 0.007184369955211878
Epoch: 24, Loss: 0.0016255333321169019
Epoch: 25, Loss: 0.019872212782502174

#**Evaluation**

In [25]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9844