In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True) #drop first and last column

In [8]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# **Train Test Split**

syntax: df.iloc[rows, columns] , iloc means index-based selection.

**df.iloc[ : , 1 : ] ----->  all rows , columns 1 → end**

**df.iloc[:, 0]** ----> all rows,column 0 , Column 0 is the diagnosis column.

**test_size = 0.2** -----> 20% → test set ,80% → training set

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#**Scaling**

In [10]:
scaler = StandardScaler() #This creates the scaler object.Think of it as a tool that will learn: feature means,feature standard deviations.But nothing happens yet.

X_train = scaler.fit_transform(X_train) #Two things happen here.
#Step 1:— fit() The scaler learns statistics from the training data.For each feature it calculates:mean standard deviation
#Step 2:— transform() Then it scales the training data using:(𝑥−𝑚𝑒𝑎𝑛)/𝑠𝑡𝑑 So fit_transform() means: learn statistics + scale the data

X_test = scaler.transform(X_test)
#We DO NOT use fit_transform here.We only use: transform() Why? Because we must use the same statistics learned from training data.
#If we ran fit on the test data, the model would accidentally peek at the test set, which is cheating.

In [11]:
X_train

array([[ 0.80942887,  0.08031146,  0.7173363 , ..., -0.43030907,
        -0.60819196, -1.31206674],
       [-1.21289239,  0.19450431, -1.21373899, ..., -1.34389805,
        -1.59335333,  0.32940124],
       [-0.33176475, -0.26702514, -0.33434674, ..., -0.50725876,
        -0.18953991, -0.2529498 ],
       ...,
       [-1.22694226, -1.70157289, -1.25003269, ..., -1.70314749,
         0.35204964, -0.12613878],
       [-0.02209412, -1.41609075, -0.03732241, ..., -0.17169776,
        -1.21789554, -0.61487825],
       [ 1.6610231 ,  0.72026725,  1.61842134, ...,  1.89990863,
        -0.20781441, -0.41785855]])

In [13]:
y_train #notice it gives strings and nn cant work on that , that is why we will have to transform these into numbers through label encoding

157    B
97     B
79     B
106    B
26     M
      ..
359    B
392    M
140    B
528    B
18     M
Name: diagnosis, Length: 455, dtype: object

#**Label Encoding**

In [14]:
encoder = LabelEncoder() #This creates a label encoder object.It will learn how to map labels: B → 0 , M → 1


y_train = encoder.fit_transform(y_train) #Two things happen:
#Step 1:— fit()  The encoder looks at the training labels and finds unique classes: [B, M] It assigns numbers: B → 0 M → 1
#Step 2:— transform()  It converts the labels. Example:  [M, B, B, M] becomes [1, 0, 0, 1]


y_test = encoder.transform(y_test) #we must use the same mapping learned from the training set.
#If we ran fit on the test set, we might accidentally create a different mapping, which would break the model.

In [15]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

#**Numpy Arrays to PyTorch Tensors**

In [16]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

#**Definig The Model**

In [17]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

#Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25

In [20]:
# define loss function
loss_function = nn.BCELoss() #binaryCrossEntropy

#**Training Pipline**

In [21]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) #The optimizer updates the weights of the model using gradients.  new_weight = old_weight - learning_rate * gradient

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()  #Now the optimizer updates the weights.

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.0541918277740479
Epoch: 2, Loss: 0.7183670997619629
Epoch: 3, Loss: 0.5435497164726257
Epoch: 4, Loss: 0.4505552649497986
Epoch: 5, Loss: 0.39286407828330994
Epoch: 6, Loss: 0.35294920206069946
Epoch: 7, Loss: 0.3233213722705841
Epoch: 8, Loss: 0.30024027824401855
Epoch: 9, Loss: 0.2816162705421448
Epoch: 10, Loss: 0.26618319749832153
Epoch: 11, Loss: 0.25312569737434387
Epoch: 12, Loss: 0.24189285933971405
Epoch: 13, Loss: 0.23209768533706665
Epoch: 14, Loss: 0.22345975041389465
Epoch: 15, Loss: 0.21576999127864838
Epoch: 16, Loss: 0.20886921882629395
Epoch: 17, Loss: 0.2026335448026657
Epoch: 18, Loss: 0.19696500897407532
Epoch: 19, Loss: 0.19178485870361328
Epoch: 20, Loss: 0.1870289444923401
Epoch: 21, Loss: 0.18264438211917877
Epoch: 22, Loss: 0.1785871684551239
Epoch: 23, Loss: 0.1748201847076416
Epoch: 24, Loss: 0.1713118702173233
Epoch: 25, Loss: 0.1680353581905365

#**Evaluation**

In [22]:
# model evaluation
with torch.no_grad(): #Don't build the computation graph , Don't store gradients
  y_pred = model.forward(X_test_tensor) #This runs a forward pass using the test data.
  y_pred = (y_pred > 0.5).float()  # > 0.5 → class 1 , ≤ 0.5 → class 0
  accuracy = (y_pred == y_test_tensor).float().mean() #This calculates how many predictions were correct.
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5260080099105835